events {
    worker_connections 1024;
}

http {
    upstream app_servers {
        server app1:2137;
        server app2:2137;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://app_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            # Simple failover logic
            proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
        }
    }
}
